### ISSUE TITLE
There is a need for a new endpoint 'auth/status'

### ISSUE THREAD

**Issue by AlehBarushka** [windownik/Deverant_API#5]
It is necessary to create a method on the backend that will send me the data of the registered user (email, userName and activation status).

For example: 
**req** to - https://server/auth/status

**req body or query string** (preferably req body) - auth_token - ************************* 

**res** - if the auth_token value is valid, you send a response with a status code _200_ and a json object with the fields: `{
  email: 'expample@ex.com',
  userName: 'expample'
};`

**res** - if the auth_token value is not valid or missing, you send a response with a status code _401_ and an error with message: _пользователь не авторизован!_

**Comment by windownik** [comment]
I create new endpoint getMe
